#1
framework: mocha
postMerge: 
  pattern: 
    - "test/**/*.spec.js"
postRun: 
  command: 
    - "node --version"  
preMerge: 
  pattern: 
    - "test/**/*.spec.js"
preRun: 
  command: 
    - npm ci
parallelism: 2
smartRun: false
